---
- name: "Añadir a exports"
  lineinfile:
    path: /etc/exports
    state: present
    line: "{{ nfs_dir }}{{ item }}"
  with_items: groups['ALL'] 
- name: "Reinicia servicio"
  ansible.builtin.systemd:
    daemon_reload: yes
    state: enabled
    name: nfs-server.service
- name: "Recarga exports"
  command: exportfs -r
- name: ""
  command: exportfs -s
  register: result
- name: "muestro el resultado de las modificaciones con la salida del comando anterior"
  ansible.builtin.debug:
    msg: "{{ result }}"
...        
