---
- name: "Instalar Chrony"
  package:
    name: 
     - chrony
    state: latest
- name: "Verificar ejecución de Chrony"
  systemd: 
    name: chronyd
    state: started
    daemon_reload: yes
    enabled: yes
- name: "Configuro zona horaria"
  community.general.timezone:
    name: Europe/Madrid
...
