---
- name: "Cambio de nombre de host"
  hostname:
    name: "{{ inventory_hostname }}"
  when:
    ansible_fqdn != ansible_ssh_host
- name: "Reinicio de host"
  become: true
  shell: shutdown -r && sleep 2
  async: 1
  poll: 0
  ignore_errors: True
- name: "Esperando fin de reinicio del servidor"
  pause:
    seconds: 30
- name: "Fix /etc/hosts removing the old hostname"
  tags:
    - hosts
  lineinfile:
    state: present
    dest: /etc/hosts
    line: "{{ ansible_default_ipv4.address }} {{ inventory_hostname }} {{ ansible_hostname }}"
    regexp: "^{{ ansible_default_ipv4.address }}"
  when:
    ansible_fqdn != inventory_hostname
- name: "Validate ansible_fqdn == inventory_hostname"
  tags:
    - validate
  assert:
    that:
      ansible_fqdn == inventory_hostname
...
