---
 - name: "Cambio de nombre de host"
   hostname:
     name: "{{ inventory_hostname }}"
   when:
     ansible_fqdn != ansible_ssh_host
 - name: "Sustituye antiguo nombre de host en /etc/hosts"
   tags:
     - hosts
   lineinfile:
     state: present
     dest: /etc/hosts
     line: "{{ ansible_default_ipv4.address }} {{ inventory_hostname }} {{ ansible_hostname }}"
     regexp: "^{{ ansible_default_ipv4.address }}"
   when:
     ansible_fqdn != inventory_hostname
 - name: "Comprueba el cambio"
   tags:
     - validate
   assert:
     that:
       ansible_fqdn == inventory_hostname
...
