---
- name: "Añadir a exports"
  lineinfile:
    path: /etc/hosts
    state: present
    line: "{{ item }}"
  with_items:
    - '10.0.1.11 master master.tarea2.unir'
    - '10.0.1.12 worker1 worker1.tarea2.unir'
    - '10.0.1.11 master nfs.tarea2.unir'
...
