---
- name: "Añadir a exports"
  lineinfile:
    path: /etc/hosts
    state: present
    line: "{{ item }}"
  with_items:
    - '192.168.1.11 master-vm master-vm.tarea2.unir'
    - '192.168.1.12 worker1-vm worker1-vm.tarea2.unir'
...
