---
- name: "Añadir a exports"
  lineinfile:
    path: /etc/hosts
    state: present
    line: "{{ item }}"
  with_items:
    - '192.168.1.215 master kubemaster.acme.es'
    - '192.168.1.216 node1 kubenode1.acme.es'
    - '192.168.1.217 node2 kubenode2.acme.es'
    - '192.168.1.218 nfs nfs.acme.es'
...
