---
- name: "Check para comprobar que está comentado. Mantener idempotencia."
  lineinfile:
    dest: /etc/fstab
    line: '#/dev/mapper/cs-swap'
  check_mode: yes
  register: result
  ignore_errors: true
- name: "Comenta linea SWAP en /etc/fstab"
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '/dev/mapper/cs-swap'
    replace: '#/dev/mapper/cs-swap'
  when: result is failed
- name: swap - disable swap
  command: swapoff --all
  ignore_errors: yes
...
