---
- name: "Desabilita SELinux"
  ansible.posix.selinux:
    state: disabled
  register: result
  notify:
    - Reinicio host
- name: "Imprimo informacion de la tarea anterior"
  ansible.builtin.debug:
    var: result
...
