---
- name: "Check or install nfs-utils"
  dnf: 
  name: {nfs-utils, nfs4-acl-tools}
    state: latest
- name: "Monta unidad en máquina huesped"
  mount:
    fstype: nfs
    opts: defaults
    dump: 0
    passno: 0
    state: mounted
    src: "nfs:/srv/nfs"
    path: "/srv/nfs"
  register: salida
- name: "Muestro resultado check anterior"
  ansible.builtin.debug:
    msg: "{{ salida }}"
- name: "Recarga unidades"
  ansible.posix.mount:
    path: /srv/nfs
    state: remounted
- name: Monta todos los filesystems
  shell: mount -a   
...
