---
- name: "Actualiza los paquetes con dnf"
  dnf:                                                 
    name: "*"                                          
    state: latest                                      
  register: result                                     
- name: "Imprime informacion de la tarea anterior"
  ansible.builtin.debug:                               
    var: result                                        
- name: "Instala Python"
  dnf:
    name: python3
    state: installed
- name: "Instala Epel-release"
  dnf:
    name: epel-release
    state: installed
- name: "Instala Ansible"
  dnf:
    name: ansible
    state: installed
...
