---
- name: "Crear directorio para NFS"
  file:
    path: /opt/deployment
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0775
    recurse: yes
- name: "Copy Manifest file to master"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /opt/deployment
    mode: '0644'
  with_fileglob: "files/*"
...
