---
- name: Instalar elinks para pruebas
  shell: yum install --enablerepo=powertools elinks -y
- name: "Crear directorio para NFS"
  file:
    path: "{{ appWorkDir }}{{ appPrefix }}/"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0775
    recurse: yes
- name: "Copy Manifest file to master"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ appWorkDir }}{{ appPrefix }}/"
    mode: '0644'
  with_fileglob: "files/{{ appPrefix }}/*"
...
