- name: Copy the join command to server location
  copy:
    src: ../../k8s-master/files/join-command.txt
    dest: /tmp/join-command.sh
    mode: 0770
  register: copy_join
- name: Join the node to cluster
  command: sh /tmp/join-command.sh
  register: kubewjoin
  ignore_errors: yes
