---
apiVersion: v1
kind: Service
metadata:
    name: resty-service
    namespace: apirest
spec:
    selector:
      app: simplespringapprest
    ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rest-ingress
  namespace: apirest
  labels:
    app: simplespringapprest
  annotations:
      haproxy.org/path-rewrite: "/greeting/"
spec:
  rules:
  - host: springboot.unir
    http:
      paths:
      - path: "/greeting"
        pathType: "Prefix"
        backend:
          service:
            name: resty-service
            port:
              number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplespringapprest
  namespace: apirest
  labels:
    app: simplespringapprest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simplespringapprest
  template:
    metadata:
      labels:
        app: simplespringapprest
    spec:
      containers:
      - name: simplespringapprest
        image: ivaner/springapprest
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /greeting
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-configmap
  namespace: apirest
data:
  servers-increment: "42"
  ssl-redirect: "OFF"
