---
- name: "Abrir puertos firewall"
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - 6443/tcp
    - 2379-2380/tcp
    - 10250-10252/tcp
    - 10255/tcp
  register: result
- name: "Reiniciar firewalld"
  systemd:
    name: firewalld
    state: reloaded
  when: result is changed
- name: "Reglas de acceso de los Workers"
  firewalld:
    rich_rule: "rule family=ipv4 source address={{ item }}/32 accept"
    permanent: true
    state: enabled
  with_items: groups['WORKERS']
...
