---
- name: "Descarga imagenes"
  command: kubeadm config images pull
- name: "Inicializa pod network"
  command: kubeadm init --pod-network-cidr 192.169.0.0/16
  ignore_errors: yes
  #- name: populate /etc/environment
  #  lineinfile:
  #    dest: "/etc/environment"
  #    state: present
  #    regexp: "^{{ item.key }}="
  #    line: "{{ item.key }}={{ item.value}}"
  #  with_items: "{{ os_environment }}"
- name: "Crear directorio para configuracion Kuberntetes y uso con perfil root"
  file:
    path: /root/.kube/ 
    state: directory
    owner: aristoteles
    group: aristoteles
    mode: 0774
    recurse: yes
- name: "Copy archivo conf"
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes
    owner: root
    group: root
    mode: 0600
- name: "Configuro network provider con Calico Azure"
  command: kubectl apply -f https://docs.projectcalico.org/manifests/canal.yaml
  environment:
    KUBECONFIG: '/etc/kubernetes/admin.conf'
...
