---

- name: "Configuro variable persistente"
  shell: echo 'KUBECONFIG=/etc/kubernetes/admin.conf' >> /etc/environment

- name: "Descarga imagenes"
  shell: kubeadm config images pull

- name: "Inicializa pod network"
  shell: kubeadm init --pod-network-cidr 192.169.0.0/16
  ignore_errors: true

- name: "Compruebo la red configurada"
  shell: kubectl get nodes -o jsonpath='{.items[*].spec.podCIDR}'
  register: salida1
- debug: msg= "{{ salida1 }}"

- name: "Crear directorio para configuracion Kuberntetes y uso con perfil adminDevOps"
  file:
    path: /home/adminDevOps/.kube/ 
    state: directory
    owner: adminDevOps
    mode: 0774
    recurse: yes

#- name: "Crea un usuario administrador adicional: kubeadmin y se crea clave ssh"
#  ansible.builtin.user:
#    name: kubeadmin
#    create_home: yes
#    home: /home/kubeadmin
#    skeleton: true
#    shell: /bin/bash
#    generate_ssh_key: yes
#    ssh_key_bits: 2048
#    ssh_key_file: .ssh/id_rsa

- name: "Crear directorio para configuracion Kuberntetes y uso con perfil root"
  file:
    path: /root/.kube/
    state: directory
    owner: root
    group: root
    mode: 0774
    recurse: yes

- name: "Copy archivo conf para root"
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes
    owner: root
    group: root
    mode: 0600

- name: "Copy archivo conf para adminDevOps"
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/adminDevOps/.kube/config
    remote_src: yes
    owner: adminDevOps
    mode: 0600

- name: "Agrego a Sudoers adminDevOps"
  shell: chmod 666 /etc/kubernetes/admin.conf

- name: "Configuro network provider con Calico Azure"
  shell: kubectl apply -f https://docs.projectcalico.org/manifests/canal.yaml
  ignore_errors: true
  notify:
    - Reinicio host
...
