---
- name: "Configuro variable persistente"
  shell: echo 'KUBECONFIG=/etc/kubernetes/admin.conf' >> /etc/environment
- name: "Descarga imagenes"
  shell: kubeadm config images pull
- name: "Inicializa pod network"
  shell: kubeadm init --pod-network-cidr 192.169.0.0/16
  register: salida1
  ignore_errors: true
- name: Pausa de 120 segundos
  pause:
    seconds: 120
- debug: msg= "{{ salida1 }}"
- name: "Crear directorio para configuracion Kuberntetes y uso con perfil root"
  file:
    path: /root/.kube/ 
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0774
    recurse: yes
- name: "Copy archivo conf"
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes
    owner: root
    group: root
    mode: 0600
- name: "Instalo tigera operator"
  shell: kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml
- name: "Descargo Calico custom-resources.yaml"
  shell: wget https://docs.projectcalico.org/manifests/custom-resources.yaml -O /root/.kube/custom-resources.yaml
- name: "Modifico CIDR"
  shell: sed -i 's/192.168.0.0/192.169.0.0/g' /root/.kube/custom-resources.yaml
- name: "Levanto configuraciones de custom-resources.yaml"
  shell: kubectl apply -f /root/.kube/custom-resources.yaml
- name: Pausa de 120 segundos
  pause:
    seconds: 180
- name: "Configuro network provider con Calico Azure"
  shell: kubectl apply -f https://docs.projectcalico.org/manifests/canal.yaml
  ignore_errors: true
...
