---
- name: Generate join command
  shell: kubeadm token create --print-join-command
  register: join_command
  environment:
    KUBECONFIG: '/etc/kubernetes/admin.conf'
- name: Copy join command to local file
  copy: 
    content: "{{ join_command.stdout_lines[0] }}" 
    dest: '.join-command.txt'
- name: "Recupero informacion de conexion de nodos"
  fetch:
    src: /home/aristoteles/.join-command.txt
    dest: ./files/join-command.txt 
    flat: yes
...
