---
- name: "DNF update previo"
  dnf:
    name:  "*"
    state: latest 
- name: "Instala paquete cri-o"
  dnf:
    name: cri-o
    state: latest
  register: result
- name: Print return information from the previous task
  ansible.builtin.debug:
    var: result
- name: "Inicia y activa servicio crio"
  ansible.builtin.service:
    name: crio
    enabled: yes
    state: started
...
