---
- name: "Instala los demonios de kubernetes"
  dnf:
    name: "{{ item }}"
    state: present
    disable_excludes: 'kubernetes'
  loop:
    - kubelet
    - kubeadm
    - kubectl
- name: "Inicia y activa servicio kubelet"
  ansible.builtin.service:
    name: kubelet
    enabled: yes
    state: started
...
